### ISSUE TITLE
Service Account not being created in the correct namespace

### ISSUE THREAD

**Issue by kengibous** [Panopta/kubernetes#2]
The panopta service account is getting created in the default namespace

https://github.com/Panopta/kubernetes/blob/master/panopta/templates/service-account.yaml

Does not have the namespace for the ServiceAccount, ClusterRole, ClusterRoleBinding

I believe the chart should be 
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}-serviceaccount
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Chart.Name }}-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["pods", "services", "nodes", "events", "componentstatuses", "persistentvolumes", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "patch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["metrics"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ .Chart.Name }}-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: panopta-role
subjects:
- kind: ServiceAccount
  name: {{ .Chart.Name }}-serviceaccount
  namespace: {{ .Release.Namespace }}
```
I was able to get this to work by manually applying yaml
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: panopta-serviceaccount
  namespace: panopta 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: panopta-role
  namespace: panopta 
rules:
- apiGroups: [""]
  resources: ["pods", "services", "nodes", "events", "componentstatuses", "persistentvolumes", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "patch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["metrics"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: panopta-rolebinding
  namespace: panopta 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: panopta-role
subjects:
- kind: ServiceAccount
  name: panopta-serviceaccount
  namespace: panopta 
```
